### ISSUE TITLE
Request: support outputting a JSON file with all the gigs

### ISSUE THREAD

**Issue by lirantal** [gigsboat/cli#1]
Support generating also a JSON file, along with the Markdown or others, which allows the data to be consumed via other means and consumers. For example, a frontend app that displays the data over HTML.

**Comment by itssiva24** [comment]
@lirantal  Can I try this?

**Comment by lirantal** [comment]
I'd be honored.

It would make sense that this would be part of a CLI argument but we don't yet have support for CLI args (@marquicodes is planning to work on that as part of #5). So in the meanwhile, how about you go ahead and add support for a JSON output so that the behavior is that it generates both the README.md and will generate a README.json too. Later, when @marquicodes add the CLI args support we can make it explicitly dump the json file only when `--json` is added. Sounds ok?

**Comment by itssiva24** [comment]
Yes sure, sounds good 👍
