### ISSUE TITLE
List of available options for tags and type in markdown file

### ISSUE THREAD

**Issue by gep13** [gigsboat/cli#12]
Is there somewhere that lists the available options that can/should be put into the `tags` and `type` sections in markdown files for gigs?

I didn't see anything in the readme, but worried that I might have missed something.

**Comment by lirantal** [comment]
Based on the code: https://github.com/gigsboat/cli/blob/0ea27bc8e62e47db276d33e72400e979af5ee895/src/utils/md-formatter.js#L39-L58

Supporting badges and stats for:
* Conferences
* Podcasts
* Webinars
* Meetups
* Articles

(Note the exact type per the code snippet above)

--

Really good feedback!
Best to document them in the README after that `YAML Front Matter` section I think. What do you say, and would you like to create a PR to send them over?

**Comment by gep13** [comment]
Sure!

I have raised a PR here:

https://github.com/gigsboat/cli/pull/16

Let me know if you have any comments.
