### ISSUE TITLE
Invalid markdown formatting when readme is updated

### ISSUE THREAD

**Issue by gep13** [gigsboat/cli#13]
## Expected Behavior

The generated readme.md file should contain correctly formatted markdown, which renders correctly in the repository.

## Current Behavior

The generated readme.md file contains invalid/malformed content, which means that the header doesn't render correctly, as shown here:

![image](https://user-images.githubusercontent.com/1271146/142935761-ea9435be-3e74-4bcd-acfd-42686d6d558e.png)

## Possible Solution

I haven't look into `how` the CLI works yet, so can't offer anything here at the minute

## Steps to Reproduce (for bugs)

1. Cloned template repository
1. Followed steps in readme to create first gig
1. Noted that the `Table of Contents` header doesn't render correctly
1. Manually fixed the problem
1. Added a second gig
1. Noted that the `Table of Contents` header once again was formatted incorrectly

## Context

After cloning the template repository, I added my first gig, and noticed that the `Table of Contents` header wasn't showing up correctly.  I tried manually editing it to correct the problem, which worked, but when I added another gig, it went back to the same problem, where the header wasn't showing correctly due to invalid spacing before the first `#`.

## Your Environment

This was experienced in my repository here: 

https://github.com/gep13-talks/public-speaking

Which was generated from the template repository

**Comment by gep13** [comment]
By adding a precontent section in to the gigsboat.json file, the issue with the invalid markdown for the heading has resolved itself.

You can see in this commit:

https://github.com/gep13-talks/public-speaking/commit/e9b8e0cddad6cf15ac7dc19c54c724a9ffd18447

That the heading starts at the beginning of the line, where as before, it had some spaces in front of it.

**Comment by lirantal** [comment]
Ahh yes, indeed I can see the issue and as you said - related to the customization in `gigsboat.json`
Will shoot out a fix!

**Comment by gep13** [comment]
@lirantal thanks for getting this fixed up!
