### ISSUE TITLE
Document precontent section of gigsboat.json file

### ISSUE THREAD

**Issue by gep13** [gigsboat/cli#14]
It wasn't immediately clear to me how you were getting the extra content in your readme.md file, i.e. this section:

<img width="1045" alt="2021-11-22_21-18-55" src="https://user-images.githubusercontent.com/1271146/142936739-92a70dfe-b951-46ba-9e34-3637b8fd8432.png">

Then when I went and had a look into your gigsboat.json file, it was clear how this was happening.

Can I suggest that some information be added to the readme.md here about this section, and anything else that can be added to the json file to control the generated content?

**Comment by lirantal** [comment]
Yes, you're right.

Where should we document that? in the template repo, or in the cli one?

**Comment by gep13** [comment]
>@lirantal said...
Where should we document that? in the template repo, or in the cli one?

How about both? :smile:

Could you add an empty element in the template repository version of the file, to make it clear that there "are" other elements that you can add?  What happens if there is an empty element?  Will the cli continue to work?

And then, mention the pre and post elements in the README.md of the cli repository?

**Comment by lirantal** [comment]
I think it's a good idea.
So, let's do this:
1. Create a PR to update the template repo with examplistic precontent like I have in my own stuff. Perhaps a title, some badges to follow the person on social, and a bullet list
2. Document in the `cli` repo that this exists
