### ISSUE TITLE
Add `workshop` to list of event types

### ISSUE THREAD

**Issue by gep13** [gigsboat/cli#17]
**Is your feature request related to a problem? Please describe.**

In addition to the current list of event types:

https://github.com/gigsboat/cli#type-property

I have done a couple of in-person workshop events.  These don't really fit into the current list of event types.

I would like to see an additional event type added called `workshop`.

**Describe the solution you'd like**

It should be possible to set the type property to `workshop` in the same way that you can with `conference`, `meetup`, etc.

**Describe alternatives you've considered**

It would be possible to set the type to `workshop` today, but that would mean that the events would be grouped into the `other` category, and I am of the opinion that having a dedicated group for workshop would make sense.

@lirantal If this is something that you would be interested in adding, I have a working solution that I could put up as a PR.

**Comment by lirantal** [comment]
@gep13 makes total sense, let's add it!
