### ISSUE TITLE
Request: create a gallery thumbnail view of all pictures from events as a summary for each year

### ISSUE THREAD

**Issue by lirantal** [gigsboat/cli#21]
A cool idea would be to add a sort of gallery of all images showing up as a table for a summary of the entire year.

-- 
**Update: 6/1/2022**
Have been playing a bit with the markup and was thinking that we could make the list a bit more lively by creating a sort of mosaic/thumbnail gallery of all the pictures that you collect from events (essentially I just store them as direct links to pictures on Twitter usually when people or events post them).

Some screenshots of how it looks like in my tests:
![image](https://user-images.githubusercontent.com/316371/148303152-7cb3d872-b256-422e-9e5f-dd3807fae92c.png)

For a "bigger year" with many more events it looks like this:
![image](https://user-images.githubusercontent.com/316371/148303186-48ded007-073b-4b6e-8910-c4098d39adca.png)

Some notes:
* I used both `height="50" width="100"` which might crop the pictures not respective to the image sizes but it gives a more "densed" look rather than empty spaces if some pictures are landscape whereas others are horizontal
* I was thinking we can also hide these galleries inside a collapsable/expandable `<details>` tag for the gallery but then we don't solve the next issue which is performance&bandwidth and it kinda misses the point with the picture eye-candy thing
* Performance-wise (and bandwidth) it could potentially get the page to load slow I guess and scroll heavily if there are too much images to fetch.

What do you think?

**Comment by lirantal** [comment]
@mcollina @lirantal @itssiva24 would be happy to hear what you think of it?

Especially that if I land this feature then it'll be impacting you on the next build you run so if there are any pushbacks to avoid the image gallery I should maybe consider putting this under config flag

**Comment by mcollina** [comment]
I have not added any image at all because they took too long to collect. This might be the push that I need to get it done.

Having an automated utility to extract the images from youtube would be amazing.

**Comment by lirantal** [comment]
Landed this one.
If you want to opt out you need to have the following `gigsboat.json` config:

```json
"output": {
  "includePictureGalleryYearly": false
}
```
