### ISSUE TITLE
Generate a static website!

### ISSUE THREAD

**Issue by mcollina** [gigsboat/cli#24]
It would be great if gigsboat could generate a static website from the data in the repository.

**Comment by lirantal** [comment]
So simply an HTML output instead of the current Markdown, yes?

**Comment by mcollina** [comment]
I think that would be amazing. Or provide some APIs / module that somebody can use to hook a gigsboat repo/doc structure to elevently or analog.

**Comment by estherixz** [comment]
I would like to work on this, are there any pointers? I explored a bit eleventy as an option and it seems like a good way to go. How about an option for automatic github pages deployment?

**Comment by mcollina** [comment]
That would be awesome for me, wdyt @lirantal?

**Comment by lirantal** [comment]
Definitely feel free to take this up @estherixz 

Just wondering whether we need to be basing this on eleventy or use a simpler solution like a simple templating engine for the HTML output?

As for GitHub Pages, that would be lovely too. Let's make sure we keep the concerns of output (the HTML) separated from deployment (GitHub Pages) so they can both be extended and maintained separately. Also, preferably they should come in through different PRs.

**Comment by estherixz** [comment]
Great, thank you! I already started working on a draft, only it wasn't on a state to raise a PR yet, but maybe I'll open a draft PR soon to get some early feedback

**Comment by estherixz** [comment]
@lirantal and @mcollina 

I have opened 3 PRs related to this issue and I'd love both your feedback.

[First one](https://github.com/gigsboat/cli/pull/31) is documentation on very simple steps for how to deploy with github pages and jekyll. There's more documentation in github pages for further customisation to which I'm linking.

[Second](https://github.com/gigsboat/cli/pull/32) is also docs update on some steps to enable a very basic 11ty starter and steps to run. That one is a bit more complicated, even though the starter is very basic, there's a bit more involved.

[Last](https://github.com/gigsboat/gigs-template/pull/4) I have added the basic 11ty starter files, that I'm describing in the docs PR into the template. Not sure if we should couple 11ty with the starter, which is I proposed an additional template. But that would create maintenance issues so maybe we can consider something like a plugin.

@mcollina I hope this is what you were looking for. There's not much availability for very granular content customisation atm, but this can probably be looked at once there's a json output in addition to the markdown generated file.

Let me know your thoughts. :)

**Comment by estherixz** [comment]
Maybe my last comment, the edit, was more confusing rather than helpful. The PRs mentioned above are ready for review now.

https://github.com/gigsboat/cli/pull/31
https://github.com/gigsboat/cli/pull/32
https://github.com/gigsboat/gigs-template/pull/4

Mateo has already checked I believe, but @lirantal if you don't like this approach let me know and I'll make amendments :)

**Comment by lirantal** [comment]
@estherixz I've merged them all but there's on pull request which we left you comments for potentially some open items that need to be resolved - whenever you can get to it.

**Comment by radomird** [comment]
@lirantal I've copied the remaining issue from the [PR](https://github.com/gigsboat/cli/pull/31#issuecomment-1037288614):

> There's some issue with the specific format of the table in combination with the way jekyll renders it, I'll look into it, see if I can find a simple solution

I'll take a look at it.

**Comment by radomird** [comment]
@lirantal & @estherixz The main issue was that GH Pages are automatically deployed from the root. Since GH Pages use jekyll to generate the pages it requires certain configuration update and also the files have to have a specific syntax. I've updated the template to support this. You can check it out in this [PR](https://github.com/gigsboat/gigs-template/pull/5).

**Comment by lirantal** [comment]
Thank you @radomird, taking a look and will follow-up on it tomorrow!

**Comment by mcollina** [comment]
Works beautifully for me! https://mcollina.github.io/public-speaking/

**Comment by lirantal** [comment]
Thanks @radomird, will merge your PR to the gigs-template repo 🚀

**Comment by radomird** [comment]
> Thanks @radomird, will merge your PR to the gigs-template repo 🚀

Thank you!
