### ISSUE TITLE
Link to the talk document inside the README

### ISSUE THREAD

**Issue by mcollina** [gigsboat/cli#25]
It would be great if the README linked to the talk `.md` file on the title.

**Comment by gep13** [comment]
@mcollina I am not sure if I follow exactly what you are suggesting here.  Can you elaborate?  Perhaps with a screenshot of what you would expect?

**Comment by lirantal** [comment]
If I understood Matteo correctly, then he'd like that when you click on the talk title itself then it would take you to the page's data file. I've actually was trying that myself a couple of weeks back and wanted it to do the same :)
