### ISSUE TITLE
Request: add yargs to support command line arguments for the CLI

### ISSUE THREAD

**Issue by lirantal** [gigsboat/cli#5]
The arguments should support at the very least the config options we have with `gigsboat.json`

Initial MVP to add support here, would be:
1. `--help` / `-h` flag for showing the standard help CLI output
2. `--config` / `-c` for pointing out the config file location (right now the code looks for a default location of the same directory it was running from

In the future, a follow up PR can then add more:
- `--debug` / `-d` to add debug output (along with adding various `debug()` points across the codebase using the `debug` dep) 
- `--json` / `-j` to process the output as json 
- `--outfile` / `-o` to save the output to a specific filename/path (whether it is a README.md file or the json output)

**Comment by marquicodes** [comment]
I would like to work on this issue.

**Comment by lirantal** [comment]
That would be awesome, thank you @marquicodes 🙏
