### ISSUE TITLE
Request: add events bucketed by type

### ISSUE THREAD

**Issue by lirantal** [gigsboat/cli#7]
Right now, evens are just bucketed by the year.
Add the ability to bucket the events into type (and inside it, they should be sorted from the latest date descending order)

**Comment by SagarPandita0** [comment]
@lirantal Hello, I wish to contribute to this Issue!

**Comment by lirantal** [comment]
Sure thing @SagarPandita0 
I think some other issues might be better as a first issue if you're just starting out, like https://github.com/gigsboat/cli/issues/9 or https://github.com/gigsboat/cli/issues/1

**Comment by SagarPandita0** [comment]
Yes it seems I should start with some other issue. I have found a spelling mistake in the Readme file, can I raise an issue for that?

**Comment by lirantal** [comment]
Of course, please do!

**Comment by lirantal** [comment]
I think with #1 implemented we can close this idea and instead anyone can implement whichever buckets they wish by scanning through the JSON file.
